### ISSUE TITLE
WSL support?

### ISSUE THREAD

**Issue by lunasorcery** [lunasorcery/pridecat#3]
If someone can verify that this works on WSL that'd be great so we can get the documentation updated.

**Comment by abbbey** [comment]
Works for me! Ran "make", followed by a "sudo make install".
![pride_wsl](https://user-images.githubusercontent.com/67073161/84940632-f7f68c80-b094-11ea-8860-5c9492834dea.png)

Used commit bbbf7a33 btw (which has the includes fix)

**Comment by lunasorcery** [comment]
Thanks!

Also verified by [n0i0b on twitter](https://twitter.com/n0i0b/status/1273332138843279360) so I'm happy to tweak the docs to reflect this.

Documentation updated in 3f78e4be7490849e902ab373915a135b415b3c1f.
