### ISSUE TITLE
Support for black/brown colors in addition to LGBT+ colors?

### ISSUE THREAD

**Issue by lizthegrey** [lunasorcery/pridecat#4]
https://www.them.us/story/ipride-flag-redesign-black-brown-trans-pride-stripes

**Comment by lunasorcery** [comment]
How's this look?
Changes in 361449ca5277d1e1f01efcae24691866cefa3bfc

<img width="584" alt="Screenshot 2020-06-17 at 20 49 23" src="https://user-images.githubusercontent.com/2166769/84943428-3bc0b480-b0dc-11ea-9c42-0080e177ff6d.png">

**Comment by noiob** [comment]
was about to PR this 😄 https://github.com/noiob/pridecat/commit/8ddaab728fbc057ac6f95ac4df228d05529d2749
![grafik](https://user-images.githubusercontent.com/8197071/84944769-952de100-b0e6-11ea-8027-158d98efc9dd.png)

**Comment by lizthegrey** [comment]
Looks good! Might be necessary to set a background in addition to foreground color to ensure that the black text is readable.
